# Generated by Django 5.0.4 on 2024-07-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_envios_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='id_transaccion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
