# Generated by Django 5.0.4 on 2024-07-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_categoria_animal_producto_animal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='orden_producto',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='orden_producto',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Orden_Producto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
