# Generated by Django 5.0.4 on 2024-09-12 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_producto_animal_remove_producto_marca_and_more'),
        ('ordenes', '0002_alter_orden_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
